import { GoogleGenAI, GenerateContentResponse, Part } from "@google/genai";
import { StyleCategory } from "../types";

// Initialize Gemini Client
// @ts-ignore
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const MODEL_NAME = 'gemini-2.5-flash-image';

/**
 * Helper to convert Blob/File to Base64 string (without the data URL prefix for the API)
 */
export const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const result = reader.result as string;
      // Remove the data:image/xxx;base64, prefix
      const base64 = result.split(',')[1];
      resolve(base64);
    };
    reader.onerror = error => reject(error);
  });
};

/**
 * Helper to extract image from response
 */
const extractImageFromResponse = (response: GenerateContentResponse): string | null => {
  if (!response.candidates || !response.candidates[0] || !response.candidates[0].content.parts) {
    return null;
  }

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData && part.inlineData.data) {
      return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
    }
  }
  return null;
};

/**
 * Generates an outfit based on an input image and a specific style.
 */
export const generateOutfitForStyle = async (
  baseImageBase64: string, 
  style: StyleCategory
): Promise<string> => {
  const prompt = `
    Act as a high-end fashion stylist. 
    I have an item of clothing (shown in the image). 
    Create a complete, stylish ${style} outfit featuring this item.
    Generate a high-quality "flat-lay" fashion photography image of the complete outfit laid out on a clean, neutral background.
    Ensure the original item is the centerpiece, surrounded by matching accessories, shoes, and complementary clothing.
    The image should be photorealistic and aesthetically pleasing.
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg', // Assuming jpeg/png, API handles standard types
              data: baseImageBase64
            }
          },
          { text: prompt }
        ]
      }
    });

    const imageUrl = extractImageFromResponse(response);
    if (!imageUrl) {
      throw new Error("No image generated by the model.");
    }
    return imageUrl;
  } catch (error) {
    console.error(`Error generating ${style} outfit:`, error);
    throw error;
  }
};

/**
 * Edits an existing outfit image based on a user's text prompt.
 */
export const editOutfitImage = async (
  imageBase64: string,
  instruction: string
): Promise<string> => {
  // We need to strip the prefix if it exists because we might be passing the data URL from state
  const rawBase64 = imageBase64.includes(',') ? imageBase64.split(',')[1] : imageBase64;

  const prompt = `
    Edit this fashion flat-lay image according to the following instruction: "${instruction}".
    Maintain the flat-lay style and high quality. 
    Keep the core composition similar unless asked to change it significantly.
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: rawBase64
            }
          },
          { text: prompt }
        ]
      }
    });

    const imageUrl = extractImageFromResponse(response);
    if (!imageUrl) {
      throw new Error("No image generated during edit.");
    }
    return imageUrl;
  } catch (error) {
    console.error("Error editing outfit:", error);
    throw error;
  }
};